@tool
extends RefCounted

const UI_TEXT := {
	"zh": {
		"send": "发送",
		"stop": "停止",
		"new_session": "新会话",
		"doctor": "诊断",
		"extensions": "扩展",
		"commands": "命令",
		"memory": "记忆",
		"reset": "重置",
		"input_placeholder": "向 AI Agent 提问...",
		"idle": "空闲",
		"waiting_model": "等待模型响应...",
		"waiting_confirm": "等待工具确认",
		"executing": "正在执行工具",
		"compacting": "正在压缩会话历史",
		"confirm_title": "需要确认的工具调用",
		"apply": "应用",
		"reject": "拒绝",
		"always_allow": "本会话内自动允许相似低风险更改",
		"high_risk_hint": "执行类或高风险工具需要每次手动确认。",
		"interrupted": "已停止当前请求，晚到的响应和事件不会继续显示。",
		"new_session_started": "已创建新会话：%s",
		"pending_notice": "上一次工具结果还没有回传。你可以丢弃待回传结果继续当前会话，或重置整个会话。",
		"discard_pending": "丢弃待回传结果",
		"recovered_pending": "已恢复会话 %s，存在待处理回合 %s。继续发送消息前请先处理或重置。",
		"recovery_dismissed": "已忽略恢复信息，会话已重置。",
		"service_manual": "AI 服务未自动启动。请连接 %s，令牌：%s",
		"service_failed": "服务启动失败：%s",
		"service_manual_full": "请手动启动服务。Base URL：%s  Token：%s",
		"event_user": "消息已提交%s。",
		"event_with_context": "，包含项目上下文",
		"event_error": "错误：%s",
		"event_reset": "会话已重置。",
		"event_config": "配置已更新（%s）。",
		"event_compact": "已压缩会话历史：%s 个 frame，移除 %s 条消息，保留最近 %s 条，保留待处理：%s。",
		"event_unknown": "事件：%s %s",
		"history_restored": "已恢复上次会话记录：%s 条。",
		"event_delegate": "Task(%s)",
		"event_model_fallback": "主模型不可用，已切换到备用模型：%s -> %s",
		"event_tool_start": "%s(%s)",
		"event_tool_done": "%s 完成",
		"event_tool_done_count": "%s 完成（%d 个结果）",
		"event_tool_failed": "%s 出错",
		"tool_read_lines": "读取了 %s 行",
		"tool_wrote_lines": "已写入 `%s`（%s 行）",
		"tool_run_result": "%s（exit=%s）",
		"tool_items_count": "返回 %s 条结果",
		"tool_done": "完成",
		"tool_done_path": "完成：`%s`",
		"tool_rejected": "已拒绝",
		"tool_error_detail": "出错：%s",
		"tool_unknown_error": "未知错误",
		"rejected_turn_ended": "已拒绝本次工具调用，会话已结束，可以继续发送新消息。",
		"history": "历史",
		"history_empty": "无历史会话",
		"switch_session_empty": "（无历史记录）"
	},
	"en": {
		"send": "Send",
		"stop": "Stop",
		"new_session": "New Chat",
		"doctor": "Doctor",
		"extensions": "Extensions",
		"commands": "Commands",
		"memory": "Memory",
		"reset": "Reset",
		"input_placeholder": "Ask the AI agent...",
		"idle": "Idle",
		"waiting_model": "Waiting for model...",
		"waiting_confirm": "Waiting for confirmation",
		"executing": "Executing tools",
		"compacting": "Compacting conversation history",
		"confirm_title": "Confirm tool calls",
		"apply": "Apply",
		"reject": "Reject",
		"always_allow": "Always allow similar low-risk changes in this session",
		"high_risk_hint": "Execution or high-risk tools must be confirmed every time.",
		"interrupted": "Current request stopped. Late responses and events will not be shown.",
		"new_session_started": "New session created: %s",
		"pending_notice": "The previous tool results have not been submitted yet. Discard them to continue this session, or reset the whole session.",
		"discard_pending": "Discard pending results",
		"recovered_pending": "Recovered session %s with a pending turn %s. Resolve it or reset before sending another message.",
		"recovery_dismissed": "Recovery dismissed; session was reset.",
		"service_manual": "AI service was not auto-started. Connect to %s with token: %s",
		"service_failed": "Service failed to start: %s",
		"service_manual_full": "Start the service manually. Base URL: %s  Token: %s",
		"event_user": "Message submitted%s.",
		"event_with_context": " with project context",
		"event_error": "Error: %s",
		"event_reset": "Session was reset.",
		"event_config": "Configuration changed (%s).",
		"event_compact": "Compacted conversation history: %s frame(s), %s message(s) removed, %s recent kept, pending preserved: %s.",
		"event_unknown": "Event: %s %s",
		"history_restored": "Restored previous session history: %s item(s).",
		"event_delegate": "Task(%s)",
		"event_model_fallback": "Primary model unavailable, switched to fallback model: %s -> %s",
		"event_tool_start": "%s(%s)",
		"event_tool_done": "%s done",
		"event_tool_done_count": "%s done (%d result(s))",
		"event_tool_failed": "%s failed",
		"tool_read_lines": "Read %s lines",
		"tool_wrote_lines": "Wrote `%s` (%s lines)",
		"tool_run_result": "%s (exit=%s)",
		"tool_items_count": "Returned %s item(s)",
		"tool_done": "Done",
		"tool_done_path": "Done: `%s`",
		"tool_rejected": "Rejected",
		"tool_error_detail": "Error: %s",
		"tool_unknown_error": "Unknown error",
		"rejected_turn_ended": "Rejected this tool call. The turn has ended; you can send a new message.",
		"history": "History",
		"history_empty": "No session history",
		"switch_session_empty": "(no history)"
	}
}


static func table(lang: String) -> Dictionary:
	var normalized := lang
	if not UI_TEXT.has(normalized):
		normalized = "zh"
	return UI_TEXT.get(normalized, UI_TEXT["zh"])


static func text(lang: String, key: String) -> String:
	var resolved := table(lang)
	return str(resolved.get(key, key))
